In [33]:
%pip install pandas numpy 
import pandas as pd
import numpy as np

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (1.3.4)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (1.20.3)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [34]:
dataframe = pd.read_csv('d:/Downloads/TADPOLE_D1_D2.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,745,746,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,770,771,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,794,795,797,798,799,800,801,802,803,804,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
print(dataframe.head())

   RID        PTID VISCODE  SITE  D1  D2 COLPROT ORIGPROT   EXAMDATE DX_bl  \
0    2  011_S_0002      bl    11   1   1   ADNI1    ADNI1   9/8/2005    CN
1    3  011_S_0003      bl    11   1   0   ADNI1    ADNI1  9/12/2005    AD
2    3  011_S_0003     m06    11   1   0   ADNI1    ADNI1  3/13/2006    AD
3    3  011_S_0003     m12    11   1   0   ADNI1    ADNI1  9/12/2006    AD
4    3  011_S_0003     m24    11   1   0   ADNI1    ADNI1  9/12/2007    AD

   ...  PHASE_UPENNBIOMK9_04_19_17  BATCH_UPENNBIOMK9_04_19_17  \
0  ...
1  ...                       ADNI1                 UPENNBIOMK9
2  ...
3  ...                       ADNI1                 UPENNBIOMK9
4  ...

  KIT_UPENNBIOMK9_04_19_17  STDS_UPENNBIOMK9_04_19_17  \
0
1            P06-MP02-MP01            P06-MP02-MP01/2
2
3            P06-MP02-MP01            P06-MP02-MP01/2
4

  RUNDATE_UPENNBIOMK9_04_19_17 ABETA_UPENNBIOMK9_04_19_17  \
0
1                   12/14/2016                      741.5
2
3                   12/14/2016                      601.4
4

  TAU_UPENNBIOMK9_04_19_17  PTAU_UPENNBIOMK9_04_19_17  \
0
1                    239.7                      22.83
2
3                    251.7                      24.18
4

   COMMENT_UPENNBIOMK9_04_19_17  update_stamp_UPENNBIOMK9_04_19_17
0
1                           NaN                            39:54.0
2
3                           NaN                            39:54.0
4

[5 rows x 1907 columns]

In [36]:
dataframe.dropna(axis=0, how='all', thresh=None, subset=None, inplace=False)
dataframe.head()

,RID,PTID,VISCODE,SITE,D1,D2,COLPROT,ORIGPROT,EXAMDATE,DX_bl,...,PHASE_UPENNBIOMK9_04_19_17,BATCH_UPENNBIOMK9_04_19_17,KIT_UPENNBIOMK9_04_19_17,STDS_UPENNBIOMK9_04_19_17,RUNDATE_UPENNBIOMK9_04_19_17,ABETA_UPENNBIOMK9_04_19_17,TAU_UPENNBIOMK9_04_19_17,PTAU_UPENNBIOMK9_04_19_17,COMMENT_UPENNBIOMK9_04_19_17,update_stamp_UPENNBIOMK9_04_19_17
0,2,011_S_0002,bl,11,1,1,ADNI1,ADNI1,9/8/2005,CN,...,,,,,,,,,,
1,3,011_S_0003,bl,11,1,0,ADNI1,ADNI1,9/12/2005,AD,...,ADNI1,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,12/14/2016,741.5,239.7,22.83,NaN,39:54.0
2,3,011_S_0003,m06,11,1,0,ADNI1,ADNI1,3/13/2006,AD,...,,,,,,,,,,
3,3,011_S_0003,m12,11,1,0,ADNI1,ADNI1,9/12/2006,AD,...,ADNI1,UPENNBIOMK9,P06-MP02-MP01,P06-MP02-MP01/2,12/14/2016,601.4,251.7,24.18,NaN,39:54.0
4,3,011_S_0003,m24,11,1,0,ADNI1,ADNI1,9/12/2007,AD,...,,,,,,,,,,

In [4]:
print(dataframe.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12741 entries, 0 to 12740
Columns: 1907 entries, RID to update_stamp_UPENNBIOMK9_04_19_17
dtypes: float64(72), int64(8), object(1827)
memory usage: 185.4+ MB
None

In [41]:
dataframe_subset = dataframe[['Ventricles', 'Hippocampus', 'WholeBrain','Fusiform', 'Entorhinal', 'MidTemp','RAVLT_immediate','RAVLT_learning','RAVLT_forgetting','RAVLT_perc_forgetting' ,'FDG','MMSE']]
dataframe_subset.head()

,Ventricles,Hippocampus,WholeBrain,Fusiform,Entorhinal,MidTemp,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting,FDG,MMSE
0,118233.0,8336.0,1229740.0,16559.0,4177.0,27936.0,44.0,4.0,6.0,54.5455,1.36926,28.0
1,84599.0,5319.0,1129830.0,15506.0,1791.0,18422.0,22.0,1.0,4.0,100.0000,1.09079,20.0
2,88580.0,5446.0,1100060.0,14400.0,2427.0,16972.0,19.0,2.0,6.0,100.0000,1.06360,24.0
3,90099.0,5157.0,1095640.0,14617.0,1596.0,17330.0,31.0,2.0,7.0,100.0000,1.10384,17.0
4,97420.0,5139.0,1088560.0,14033.0,1175.0,16398.0,23.0,1.0,5.0,100.0000,1.03871,19.0

In [51]:
dataframe_subset.replace(np.nan,0)

,Ventricles,Hippocampus,WholeBrain,Fusiform,Entorhinal,MidTemp,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting,FDG,MMSE
0,118233.0,8336.0,1229740.0,16559.0,4177.0,27936.0,44.0,4.0,6.0,54.5455,1.36926,28.0
1,84599.0,5319.0,1129830.0,15506.0,1791.0,18422.0,22.0,1.0,4.0,100.0000,1.09079,20.0
2,88580.0,5446.0,1100060.0,14400.0,2427.0,16972.0,19.0,2.0,6.0,100.0000,1.06360,24.0
3,90099.0,5157.0,1095640.0,14617.0,1596.0,17330.0,31.0,2.0,7.0,100.0000,1.10384,17.0
4,97420.0,5139.0,1088560.0,14033.0,1175.0,16398.0,23.0,1.0,5.0,100.0000,1.03871,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...
12736,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.00000,11.0
12737,0.0,0.0,0.0,0.0,0.0,0.0,38.0,3.0,5.0,50.0000,0.00000,27.0
12738,0.0,0.0,0.0,0.0,0.0,0.0,29.0,2.0,7.0,100.0000,0.00000,27.0
12739,0.0,0.0,0.0,0.0,0.0,0.0,38.0,3.0,1.0,11.1111,0.00000,28.0
12740,0.0,0.0,0.0,0.0,0.0,0.0,32.0,0.0,5.0,83.3333,0.00000,26.0

In [57]:
dataframe_subset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12741 entries, 0 to 12740
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ventricles             7445 non-null   float64
 1   Hippocampus            6802 non-null   float64
 2   WholeBrain             7689 non-null   float64
 3   Fusiform               6469 non-null   float64
 4   Entorhinal             6469 non-null   float64
 5   MidTemp                6469 non-null   float64
 6   RAVLT_immediate        8831 non-null   float64
 7   RAVLT_learning         8831 non-null   float64
 8   RAVLT_forgetting       8805 non-null   float64
 9   RAVLT_perc_forgetting  8735 non-null   float64
 10  FDG                    3352 non-null   float64
 11  MMSE                   8932 non-null   float64
dtypes: float64(12)
memory usage: 1.2 MB

In [61]:
x=dataframe_subset.drop(['MMSE'],axis=1).values
y=dataframe_subset['MMSE'].values

In [62]:
print(x)

[[1.18233e+05 8.33600e+03 1.22974e+06 ... 6.00000e+00 5.45455e+01
  1.36926e+00]
 [8.45990e+04 5.31900e+03 1.12983e+06 ... 4.00000e+00 1.00000e+02
  1.09079e+00]
 [8.85800e+04 5.44600e+03 1.10006e+06 ... 6.00000e+00 1.00000e+02
  1.06360e+00]
 ...
 [        nan         nan         nan ... 7.00000e+00 1.00000e+02
          nan]
 [        nan         nan         nan ... 1.00000e+00 1.11111e+01
          nan]
 [        nan         nan         nan ... 5.00000e+00 8.33333e+01
          nan]]

In [60]:
print(y)

[28. 20. 24. ... 27. 28. 26.]

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [53]:
from sklearn.linear_model import Lasso
m1=Lasso()
m1.fit(x_train,y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').